version: '3.8'

services:
  web:
    build: .
    container_name: lotto_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 lotto_project.wsgi:application"