# Generated by Django 6.0.4 on 2026-05-16 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LottoPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.PositiveIntegerField()),
                ('num2', models.PositiveIntegerField()),
                ('num3', models.PositiveIntegerField()),
                ('num4', models.PositiveIntegerField()),
                ('num5', models.PositiveIntegerField()),
                ('num6', models.PositiveIntegerField()),
                ('selection_type', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], default='AUTO', max_length=6, verbose_name='선택 유형')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='구매 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
                ('lotto_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround', verbose_name='회차')),
            ],
        ),
        migrations.CreateModel(
            name='LottoWinDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win1', models.PositiveIntegerField()),
                ('win2', models.PositiveIntegerField()),
                ('win3', models.PositiveIntegerField()),
                ('win4', models.PositiveIntegerField()),
                ('win5', models.PositiveIntegerField()),
                ('win6', models.PositiveIntegerField()),
                ('bonus', models.PositiveIntegerField(verbose_name='보너스 번호')),
                ('drawn_at', models.DateTimeField(auto_now_add=True, verbose_name='추첨 일시')),
                ('lotto_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround', verbose_name='회차')),
            ],
        ),
    ]
