# Generated by Django 6.0.4 on 2026-05-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottopurchase',
            name='is_won',
            field=models.BooleanField(default=False, verbose_name='당첨 여부'),
        ),
        migrations.AddField(
            model_name='lottopurchase',
            name='winning_rank',
            field=models.CharField(default='추첨 전', max_length=10, verbose_name='당첨 등수'),
        ),
    ]
